### ISSUE TITLE
re-enable full app suite in development conductor commands

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#182]
Just by following the default set of instructions, I wound up with this, at the moment. 

what we know is that this is related to https://github.com/holochain/holochain/issues/966.

This line is the one that fails
https://github.com/holo-rea/holo-rea/blob/2cc905a7184d7292e632b2ec6df5d876ce623934/scripts/run-dev-conductor.sh#L17
Because of the size of that happ file.

We just aren't seeing the failure to install, and it's not crashing at that step even if it fails.

```
Unhandled Rejection (TypeError): appInfo is null
connect
src/App.tsx:60:4

  57 | const conn = await openConnection(process.env.REACT_APP_HC_CONN_URL as string);
  58 | const appInfo = await conn.appInfo({ installed_app_id: (process.env.REACT_APP_HC_APP_ID as string) })
  59 | 
> 60 | dnaMappings = (appInfo['cell_data'] as unknown[] as ActualInstalledCell[]).reduce((mappings, { cell_id, role_id }) => {
  61 |   const hrea_cell_match = role_id.match(/hrea_(\w+)_\d+/)
  62 |   if (!hrea_cell_match) { return mappings }
  63 | 
```

<img width="1217" alt="Screen Shot 2022-01-03 at 3 07 31 PM" src="https://user-images.githubusercontent.com/1409121/147990124-30a76dfe-60c0-4a84-b58a-d24c36701806.png">

"I've made these edits locally-"
```
$ git diff scripts/run-dev-conductor.sh
diff --git a/scripts/run-dev-conductor.sh b/scripts/run-dev-conductor.sh
index 67f30d80..abd8cee8 100755
--- a/scripts/run-dev-conductor.sh
+++ b/scripts/run-dev-conductor.sh
@@ -14,5 +14,5 @@ APP="${HOLOCHAIN_APP_PORT:-4000}"
 
 "$UTIL" s clean
 "$UTIL" s create -n 1 -d hrea_tester network quic
-"$UTIL" s call install-app-bundle ./bundles/full_suite/hrea_suite.happ
+"$UTIL" s call install-app-bundle ./bundles/obs_and_agent/hrea_obs_spec.happ
 "$UTIL" s run --all -p $APP
```

then drop this config in bundles/obs_and_agent/ and do an npm run build again before re-running conductors
```
manifest_version: "1"
name: hrea_obs_spec
description: Observation and specification modules (eg. anonymized public supply chain)
roles:
  - id: hrea_observation_1
    provisioning:
      strategy: create
      deferred: false
    dna:
      bundled: "../../happs/observation/hrea_observation.dna"
      clone_limit: 0
  - id: hrea_agent_1
    provisioning:
      strategy: create
      deferred: false
    dna:
      bundled: "../../happs/agent/hrea_agent.dna"
      clone_limit: 0
```

i got the graphiql explorer to work. 

I had to match the three names... 
hrea_obs_spec in line: "$UTIL" s call install-app-bundle ./bundles/obs_and_agent/hrea_obs_spec.happ
and:     "start": "REACT_APP_HC_APP_ID='hrea_obs_spec' REACT_APP_HC_CONN_URL='ws://localhost:4000' BROWSER=none react-scripts start",
in apps -> holorea-graphql-explorer -> package.json
with: name: hrea_obs_spec
from happ.yaml you sent me
