### ISSUE TITLE
enable for releases holorea-graphql-explorer for Holochain Launcher

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#194]
Intending to assign this issue to myself, when I have the permissions
___

add a `webhapp` folder to the root level

it is also necessary to make slight code changes to `modules/vf-graphql-holochain` AppWebsocket and also `apps/holorea-graphql-explorer`. As of holochain JS conductor version 0.2.1 there is Launcher support

would have to do:
```
cd modules/vf-graphql-holochain
npm run build
cd ../..
cd apps/holorea-graphql-explorer
npm run build
# TODO: run some command to zip it up into `build.zip` but be sure to zip the sub-files, not the folder containing them!
```

yaml file
```yaml
---
manifest_version: "1"
name: hrea
ui:
  bundled: "../apps/holorea-graphql-explorer/build.zip"
happ_manifest:
  bundled: "../bundles/full_suite_release_template/hrea_suite.happ"
```

then the command is: 
`hc web-app pack webhapp`
Then the file is
`webhapp/hrea.webhapp`

and that file would also be uploaded to a release
