### ISSUE TITLE
inter-zome RPC config cleanup pass

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#263]
It's looking like the "Planning" suite is the remaining one with indexing configuration related issues https://github.com/h-REA/hREA/issues/252 , https://github.com/h-REA/hREA/issues/254, and https://github.com/h-REA/hREA/issues/255.

 @pospi can you look at it? I have tried

**Comment by pospi** [comment]
Gonna get through as many of these as I can. Started with the `Agreement` indexing update in d93559be.

**Comment by pospi** [comment]
Finished with first item, moving it down here so as to not interfere with outstanding work-

### # 1

- [x] DNA config manifests need to be updated to match new index libs

For every `_index_zome` helper in the zome's `lib` crate, there should be a defined `index_zome:` for this zome, under a parent key of the same name as the zome (eg. `agreement`, `economic_event` etc) to pair the CRUD zome with its locally configured index. There should also be a reverse association. The entire block has this format (substituting "agreement"):

```
  agreement:
    index_zome: agreement_index
  agreement_index:
    record_storage_zome: agreement
```

Ensure all indexes are declared as `Local` or `Remote` *depending on the calling CRUD zome* (in an older version, calling context was interpreted differently). The easiest way to find a point of reference for this is to track down all `create_index!` / `update_index!` macro calls for the zome of interest and track down index defs from there, based on the relationships between each zome (as in, are they in the same DNA as the zome which called the macro, or a remote one?)

You should also whitelist any index management method(s) declared as a `Remote<>` index type in the associated `_index` zome. For example:
```
#[index_zome]
struct Agreement {
	economic_events: Remote<economic_event, realization_of>,
	commitments: Remote<commitment, clause_of>,
}
```

        yields

```
  remote_auth:
    permissions:
      - extern_id: index_agreement_economic_events
        allowed_method: [agreement_index, index_economic_events]
      - extern_id: index_agreement_commitments
        allowed_method: [agreement_index, index_commitments]
```
